services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - USER_NAME=aurelius
    command: pnpm start
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - //frontend/node_modules
    environment:
      - USER_NAME=aurelius
    command: pnpm run dev

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"  # Using port 8888 instead
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend