services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - backend_node_modules:/app/backend/node_modules  # Named volume for node_modules
    environment:
      - USER_NAME=aurelius

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules  # Named volume for node_modules
    environment:
      - USER_NAME=aurelius

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules: